---
branches:
    except:
        - donttestme

language: python

matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
        - python: 3.6
          env: TOXENV=flake8

install:
    - pip install tox

script: tox
