---
language: python
python: 3.6

env:
  - TOXENV=py36
  - TOXENV=docs
  - TOXENV=flake8

install:
    - pip install tox

script: tox

jobs:
    include:
        - stage: deploy
          script: echo "Deploying on PyPi ..."
          env:
          install:
          deploy:
              provider: pypi
              user: JosefFriedrich
              password:
                  secure: "b2h7/y0unyEE4XmuGtrRusDcg6hVfz4VCdpJUBTf8am6YpSEEGwX9h6zLj99FJsWBanQtMxh7DhDA6Alhiu3MunmznhZgLgDWxkH5/Y+Yk+xwNdoHtakHYB0dDF95q697nuxuqxvbFaLPBsSKIf0F/G8PI19+NLkO6g24/aOm9iSsMvg0uhuBINvSswBrkDw5qNvJnQTh7No5i4ntLb1/0Qg8yp7UrGiVLnNwAqIyQsOrZlsmm6U0XrMNDS3jKxcEyCquc9g9lvVuvRoVpykLadqqzPcGSRkybNyi5s4rjH2pH1kjukon2pCajDQ+Z89TisxiiIOY/ioklcSxUxvQAB9rh5TEi454BYO3tQSQ8xfiQIsTmFd5H7f2LZWX2AvfZoL5kBAvzspI0ex6rhbRDMdVNg7IF27hLKbzDWjKQi9Qlg6toOGEape/9IIY9998QDgIVj16xqqTSicjHkw2r9kvdxuoKmWtbmBBMCU7tnsSzOu7rdOraKzXqHZiJCRyroQ3cfg6hSXAPtKkhGpq9pQs9TDytj6+zflBNoSWov6ZyKNjHPlmbNGQ6N6cBLRS3/BOR6HgZW0QOBiNxkn/dXe0QNubtXCVw+1RVbXZ1eoDkmQzVYqzH68fInV+4iDhWESHsnBCHWYF1yKrngrCGfia/JwewmO+Y7qinYMclc="
              on:
                  tags: true
